### PR TITLE
Mods zoom

### PR DESCRIPTION
**Pull request by FeffyLaffy**

### CODE REVIEW

**Comment by ZTzTopia** [comment]
looks like this can directly use `m_server->get_peer()->send_variant(variant_list);` ?
or there another data in `GameUpdatePacket` variable?

**Comment by FeffyLaffy** [comment]
> looks like this can directly use `m_server->get_peer()->send_variant(variant_list);` ? or there another data in `GameUpdatePacket` variable?

i guess can use since is OnSpawn send to server i going to try it out if work

**Comment by FeffyLaffy** [comment]
image

**Comment by FeffyLaffy** [comment]
i guess is work but the OnSpawn skin still at white need to find the solution to fix it soon

**Pull request closed without merging**
